{% set name = "dicomweb-client" %}
{% set version = "0.59.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dicomweb_client-{{ version }}.tar.gz
  sha256: b06a43892f21e278c07e42e644ae7f11a1681788f11e77ef691ed404041a93cb

build:
  entry_points:
    - dicomweb_client = dicomweb_client.cli:_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py2k]

requirements:
  host:
    - python >=3.6
    - setuptools >=64
    - pip
  run:
    - python >=3.6
    - numpy >=1.19
    - requests >=2.18
    - retrying >=1.3.3
    - pillow >=8.3
    - pydicom >=2.2
    - typing-extensions >=4.0  # [py<38]

test:
  imports:
    - dicomweb_client
  commands:
    - pip check
    - dicomweb_client --help
  requires:
    - pip

about:
  home: https://github.com/ImagingDataCommons/dicomweb-client
  summary: Client for DICOMweb RESTful services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acaprez
