{% set name = "dicomweb-client" %}
{% set version = "0.61.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 24bc525322e72d215485c56acf0d0de218f284a1db73639ac8e0249822f93787

build:
  noarch: python
  entry_points:
    - dicomweb_client = dicomweb_client.cli:_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy >=1.19
    - pillow >=8.3
    - pydicom >=2.2
    - requests >=2.18
    - retrying >=1.3.3

test:
  imports:
    - dicomweb_client
  commands:
    - pip check
    - dicomweb_client --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/herrmannlab/dicomweb-client
  summary: Client for DICOMweb RESTful services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acaprez
