{% set name = "dicomweb-client" %}
{% set version = "0.59.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dd11604c99711d3fc9d223de960a1b64db3b2dcbc30592473d935e27b9243d46

build:
  entry_points:
    - dicomweb_client = dicomweb_client.cli:_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py2k]

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.19
    - pillow >=8.3
    - pydicom >=2.2
    - python
    - requests >=2.18
    - retrying >=1.3.3
    - typing-extensions >=4.0  # [py<38]

test:
  imports:
    - dicomweb_client
  commands:
    - pip check
    - dicomweb_client --help
  requires:
    - pip

about:
  home: https://github.com/herrmannlab/dicomweb-client
  summary: Client for DICOMweb RESTful services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acaprez
